name: s_house
description: A new Flutter project.

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Common
  device_info_plus: ^3.2.2
  easy_localization: ^3.0.0
  go_router: ^3.0.4
  provider: ^6.0.2
  logger: ^1.1.0
  url_launcher: ^6.0.20
  flutter_cache_manager: ^3.3.0
  after_layout: ^1.2.0
  # UI / Component
  bot_toast: ^4.0.1
  flutter_svg: ^1.0.3
  shimmer: ^2.0.0
  cached_network_image: ^3.2.0
  separated_row: ^2.0.0
  separated_column: ^2.0.0
  glass_kit: ^2.0.1
  pull_to_refresh: ^2.0.0
  persian_datetime_picker: ^2.4.0
  # Animations
  dough: ^1.0.2
  flutter_staggered_animations: ^1.0.0
  flutter_animator: ^3.2.1
  # Form
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^7.7.0
  # NoSQL Database
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  # API
  retrofit: ^3.0.1+1
  dio: ^4.0.4
  json_serializable: ^6.1.5
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  # Utils
  mobile_scanner: ^1.1.0
  share_plus: ^4.0.4
  shamsi_date: ^1.0.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.1.8
  hive_generator: ^1.1.2
  retrofit_generator: ^4.0.1
#  flutter_launcher_icons: ^0.9.2
  # replace when this package update and bug fixed
  flutter_launcher_icons:
    git:
      url: https://github.com/marcobazzani/flutter_launcher_icons.git
      ref: patch-1
  flutter_app_name: ^0.1.1

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"
  adaptive_icon_background: "assets/launcher/background.png"
  adaptive_icon_foreground: "assets/launcher/foreground.png"

flutter_app_name:
  name: "S House"

flutter:
  uses-material-design: true
  assets:
    - resources/langs/
    - assets/images/
    - assets/vectors/
    - assets/emojis/
    - assets/launcher/
  fonts:
    - family: yekanBakh
      fonts:
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-08-fat.ttf
          weight: 900
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-07-heavy.ttf
          weight: 800
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-06-bold.ttf
          weight: 700
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-05-medium.ttf
          weight: 600
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-04-regular.ttf
          weight: 500
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-03-light.ttf
          weight: 400
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-02-thin.ttf
          weight: 300
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-01-hairline.ttf
          weight: 200
        - asset: resources/fonts/yekan-bakh/fa-en/yekan-bakh-fa-en-01-hairline.ttf
          weight: 100
    - family: yekanBakhFaNum
      fonts:
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-08-fat.ttf
          weight: 900
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-07-heavy.ttf
          weight: 800
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-06-bold.ttf
          weight: 700
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-05-medium.ttf
          weight: 600
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-04-regular.ttf
          weight: 500
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-03-light.ttf
          weight: 400
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-02-thin.ttf
          weight: 300
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-01-hairline.ttf
          weight: 200
        - asset: resources/fonts/yekan-bakh/fa-num/yekan-bakh-fa-num-01-hairline.ttf
          weight: 100
    - family: iranSans
      fonts:
        - asset: resources/fonts/iran-sans/ExtraBlack.ttf
          weight: 900
        - asset: resources/fonts/iran-sans/Black.ttf
          weight: 800
        - asset: resources/fonts/iran-sans/ExtraBold.ttf
          weight: 700
        - asset: resources/fonts/iran-sans/Bold.ttf
          weight: 600
        - asset: resources/fonts/iran-sans/Medium.ttf
          weight: 500
        - asset: resources/fonts/iran-sans/Regular.ttf
          weight: 400
        - asset: resources/fonts/iran-sans/Light.ttf
          weight: 300
        - asset: resources/fonts/iran-sans/Light.ttf
          weight: 200
        - asset: resources/fonts/iran-sans/Thin.ttf
          weight: 100