// Generated by spider on 2022-06-01 09:10:05.952444

part of 'resources.dart';

class Emojis {
  Emojis._();

  static const String dislike = 'assets/emojis/dislike.png';
  static const String heart = 'assets/emojis/heart.png';
  static const String heartEyes = 'assets/emojis/heartEyes.png';
  static const String like = 'assets/emojis/like.png';
  static const String rage = 'assets/emojis/rage.png';
  static const String sad = 'assets/emojis/sad.png';
}
