// Generated by spider on 2022-05-24 08:23:34.275026

part of 'resources.dart';

class LauncherIcon {
  LauncherIcon._();

  static const String background = 'assets/launcher/background.png';
  static const String foreground = 'assets/launcher/foreground.png';
  static const String icon = 'assets/launcher/icon.png';
}
