// Generated by spider on 2022-06-01 09:10:05.956004

part of 'resources.dart';

class LauncherIcons {
  LauncherIcons._();

  static const String background = 'assets/launcher/background.png';
  static const String foreground = 'assets/launcher/foreground.png';
  static const String icon = 'assets/launcher/icon.png';
}
