// Generated by spider on 2022-06-01 09:10:05.929996

part of 'resources.dart';

class Svgs {
  Svgs._();

  static const String commentEmpty = 'assets/vectors/comment_empty.svg';
  static const String commentFillEmpty =
      'assets/vectors/comment_fill_empty.svg';
  static const String defaultEmpty = 'assets/vectors/default_empty.svg';
  static const String logo = 'assets/vectors/logo.svg';
  static const String logoTypeEn = 'assets/vectors/logo_type_en.svg';
  static const String logoTypeFa = 'assets/vectors/logo_type_fa.svg';
  static const String searchEmpty = 'assets/vectors/search_empty.svg';
}
