// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'shared/items/models/item.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 8237036456225501288),
      name: 'Item',
      lastPropertyId: const IdUid(8, 1063836990381384288),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 3528502415494919336),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7684148770269010482),
            name: 'imageIndex',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 7557365022652929584),
            name: 'pin',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 2828573854745087832),
            name: 'colorJson',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 621499679732442659),
            name: 'faName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 1063836990381384288),
            name: 'enName',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 8237036456225501288),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [1534901359950337682, 2392195050452176907],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Item: EntityDefinition<Item>(
        model: _entities[0],
        toOneRelations: (Item object) => [],
        toManyRelations: (Item object) => {},
        getId: (Item object) => object.id,
        setId: (Item object, int id) {
          object.id = id;
        },
        objectToFB: (Item object, fb.Builder fbb) {
          final pinOffset =
              object.pin == null ? null : fbb.writeString(object.pin!);
          final colorJsonOffset = object.colorJson == null
              ? null
              : fbb.writeString(object.colorJson!);
          final faNameOffset =
              object.faName == null ? null : fbb.writeString(object.faName!);
          final enNameOffset =
              object.enName == null ? null : fbb.writeString(object.enName!);
          fbb.startTable(9);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.imageIndex);
          fbb.addOffset(2, pinOffset);
          fbb.addOffset(5, colorJsonOffset);
          fbb.addOffset(6, faNameOffset);
          fbb.addOffset(7, enNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Item(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              imageIndex: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 6))
            ..pin = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 8)
            ..colorJson = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 14)
            ..faName = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 16)
            ..enName = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 18);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Item] entity fields to define ObjectBox queries.
class Item_ {
  /// see [Item.id]
  static final id = QueryIntegerProperty<Item>(_entities[0].properties[0]);

  /// see [Item.imageIndex]
  static final imageIndex =
      QueryIntegerProperty<Item>(_entities[0].properties[1]);

  /// see [Item.pin]
  static final pin = QueryStringProperty<Item>(_entities[0].properties[2]);

  /// see [Item.colorJson]
  static final colorJson =
      QueryStringProperty<Item>(_entities[0].properties[3]);

  /// see [Item.faName]
  static final faName = QueryStringProperty<Item>(_entities[0].properties[4]);

  /// see [Item.enName]
  static final enName = QueryStringProperty<Item>(_entities[0].properties[5]);
}
